(() => {
  'use strict';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function dialogo(titulo,origen){const d=document.createElement('dialog');d.className='mejora-dialogo';d.innerHTML='<button type="button" class="mejora-cerrar">Cerrar ×</button><h2></h2><div class="mejora-contenido"></div>';d.querySelector('h2').textContent=titulo;d.setAttribute('aria-label',titulo);d.querySelector('button').onclick=()=>d.close();const overflow=document.body.style.overflow;d.addEventListener('close',()=>{document.body.style.overflow=overflow;d.remove();origen?.focus();},{once:true});d.addEventListener('click',e=>{const r=d.getBoundingClientRect();if(e.target===d&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))d.close();});document.body.append(d);d.showModal();document.body.style.overflow='hidden';return d;}
  async function compartir(n,b){const u=new URL(location.origin+location.pathname);u.searchParams.set('negocio',n.slug);try{if(navigator.share)await navigator.share({title:n.nombre,url:u.href});else{const d=dialogo('Compartir '+n.nombre,b);const box=d.querySelector('.mejora-contenido');const field=document.createElement('input');field.readOnly=true;field.value=u.href;field.setAttribute('aria-label','Enlace del negocio');const copiar=document.createElement('button');copiar.textContent='Copiar enlace';copiar.onclick=async()=>{try{await navigator.clipboard.writeText(u.href);copiar.textContent='Enlace copiado';}catch{field.select();copiar.textContent='Selecciona y copia el enlace';}};const wa=document.createElement('a');wa.textContent='Compartir por WhatsApp';wa.href='https://wa.me/?text='+encodeURIComponent(n.nombre+' '+u.href);wa.target='_blank';wa.rel='noopener';box.append(field,copiar,wa);}}catch(e){if(e.name!=='AbortError')alert('No se pudo compartir. Puedes copiar la dirección de la página.');}}
  function perfil(n){const perfil=document.querySelector('.perfil-oficial');if(!perfil)return;
    for(const img of perfil.querySelectorAll('.perfil-hero-oficial img,.perfil-logo-oficial img')){if(img.closest('button'))continue;const b=document.createElement('button');b.type='button';b.className='mejora-ampliar';b.setAttribute('aria-label','Ampliar '+img.alt);img.replaceWith(b);b.append(img);b.onclick=()=>{const d=dialogo(img.alt,b),copia=document.createElement('img');copia.src=img.src;copia.alt=img.alt;copia.className='mejora-foto';copia.onerror=()=>{copia.replaceWith(document.createTextNode('No se pudo cargar la imagen.'));};d.querySelector('.mejora-contenido').append(copia);};}
    if(!perfil.querySelector('.mejora-compartir')){const b=document.createElement('button');b.type='button';b.className='accion accion-compartir mejora-compartir';b.innerHTML='<span aria-hidden="true">↗</span><div><strong>Compartir negocio</strong><small>Enviar enlace</small></div>';b.onclick=()=>compartir(n,b);perfil.querySelector('.perfil-acciones-oficial')?.append(b);}
  }
  function recopilar(lista,soloVigentes=true){const items=[];
    for(const n of lista.filter(n=>n.activo!==false)){for(const p of window.ComidaExhibicion?ComidaExhibicion.productos(n):(n.productos||[]).filter(p=>p.disponible!==false)){
      const propios=(p.gruposOpciones||[]).flatMap(g=>(g.opciones||[]).filter(o=>o.disponible!==false&&o.tipoPrecio==='propio'));
      const agregar=(o,promo,precio)=>{if(promo?.activa&&(soloVigentes?PromosProductos.vigente(promo,precio):true))items.push({n,p,o,promo,precio});};
      if(!propios.length)agregar(null,p.promocion,p.precio);for(const o of propios)agregar(o,o.promocion,o.precio);
    }}return items;
  }
  function tarjetasOfertas(){return (window.__ofertasProductos||[]).map(({n,p,o,promo,precio})=>{
    const titulo=p.nombre+(o?' · '+o.nombre:'');const foto=ComidaExhibicion.imagen(p.foto);
    return '<article class="card card-premium destacado-publicado destacado-producto-auto estilo-'+(promo.color==='dorado'?'dorado':'verde')+(promo.brillo?' promo-brillo':'')+'" role="link" tabindex="0" data-auto-slug="'+esc(n.slug)+'" data-auto-producto="'+esc(p.id)+'" aria-label="Abrir promoción de '+esc(titulo)+'"><div class="destacado-contenido"><span class="destacado-etiqueta">'+esc(PromosProductos.etiqueta(promo))+'</span><h3>'+esc(titulo)+'</h3><div class="destacado-precios">'+(promo.tipo==='precio'?'<del class="destacado-precio-anterior">'+ComidaExhibicion.dinero(PromosProductos.centavos(precio))+'</del><strong class="destacado-precio-actual">'+ComidaExhibicion.dinero(PromosProductos.centavos(promo.precio))+'</strong>':'<strong class="destacado-precio-actual">Dos iguales por '+ComidaExhibicion.dinero(PromosProductos.centavos(precio))+'</strong>')+'</div><small class="destacado-negocio">'+esc(n.nombre)+'</small></div>'+(foto?'<div class="destacado-producto-wrap" aria-hidden="true"><img class="destacado-producto-imagen" src="'+esc(foto)+'" alt="" loading="lazy"></div>':'<div class="destacado-decoracion" aria-hidden="true"></div>')+'</article>';
  });}
  function ofertas(lista){document.getElementById('ofertas-productos')?.remove();const items=recopilar(lista);const firma=JSON.stringify(items);if(firma===window.__firmaOfertasProductos)return;window.__firmaOfertasProductos=firma;window.__ofertasProductos=items;window.actualizarOfertasDestacadas?.();}
  function panelOfertas(){const lista=document.getElementById('lista-destacados');if(!lista)return;let zona=document.getElementById('promociones-productos-panel');if(!zona){zona=document.createElement('section');zona.id='promociones-productos-panel';lista.after(zona);}let negocios=[];try{negocios=JSON.parse(localStorage.getItem('exhibicionNegocios')||'[]');}catch{}
    const items=recopilar(negocios,false);zona.innerHTML='<h3>Promociones de productos</h3><p>Se toman del menú y se publican con negocios.json. No necesitas duplicarlas como anuncios.</p>'+(!items.length?'<p>No hay promociones de productos activadas.</p>':items.map(({n,p,o,promo,precio},i)=>'<article class="promocion-panel"><div><small>'+esc(n.nombre)+'</small><h4>'+esc(p.nombre)+(o?' · '+esc(o.nombre):'')+'</h4><p>'+esc(PromosProductos.etiqueta(promo))+(promo.tipo==='precio'?' · $'+Number(promo.precio).toFixed(2):'')+' · '+esc(promo.inicio)+' a '+esc(promo.fin)+'</p><p>'+ (PromosProductos.vigente(promo,precio)?'Vigente':'Fuera de vigencia o pendiente de corregir')+'</p><button type="button" data-auto-editar="'+i+'">Editar en el producto</button></div></article>').join(''));
    zona.querySelectorAll('[data-auto-editar]').forEach(b=>b.onclick=()=>{const item=items[Number(b.dataset.autoEditar)];window.editarNegocio(item.n.id);const row=Array.from(document.querySelectorAll('.producto-editor')).find(r=>r.dataset.id===item.p.id);row?.scrollIntoView({behavior:'smooth',block:'center'});});
  }
  document.addEventListener('click',e=>{const card=e.target.closest('[data-auto-slug]');if(card)window.dispatchEvent(new CustomEvent('comida-abrir',{detail:{slug:card.dataset.autoSlug,productoId:card.dataset.autoProducto}}));});
  document.addEventListener('keydown',e=>{const card=e.target.closest('[data-auto-slug]');if(card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();card.click();}});
  window.MejorasExhibicion={perfil,ofertas,tarjetasOfertas,panelOfertas};
  const dibujo='<svg viewBox="0 0 180 100" aria-hidden="true"><rect class="taxi-luz" x="65" y="7" width="50" height="21" rx="5" fill="#ffe66a"/><text x="90" y="22" text-anchor="middle" font-size="14" font-weight="bold" fill="#202020">TAXI</text><path d="M38 62L52 30H123L143 62Z" fill="#f3c328"/><path d="M58 36H86V58H49ZM93 36H119L132 58H93Z" fill="#d0effa"/><rect x="17" y="56" width="146" height="27" rx="10" fill="#ffce34"/><path d="M24 70H155" stroke="#202020" stroke-width="6" stroke-dasharray="7 7"/><circle cx="47" cy="82" r="13" fill="#25332d"/><circle cx="133" cy="82" r="13" fill="#25332d"/><circle cx="47" cy="82" r="6" fill="#ddd"/><circle cx="133" cy="82" r="6" fill="#ddd"/></svg>';
  async function iniciar(){await window.ContactosExhibicion?.lista;const config=window.ContactosExhibicion?.actual.taxi||{numero:'',activo:false};
    const normal=v=>{const n=String(v||'').replace(/\D/g,'');return n.length===10?'52'+n:n;};
    const zona=document.getElementById('compras-encargo');if(zona&&config.activo===true&&/^52\d{10}$/.test(normal(config.numero))){const s=document.createElement('button');s.type='button';s.className='mandaditos-boton taxi-boton';s.innerHTML=dibujo+'<span>Pedir taxi</span>';const pedir=zona.querySelector('.mandaditos-boton');if(pedir){const cuadro=document.createElement('section');cuadro.className='mandaditos-acceso taxi-servicio';cuadro.setAttribute('aria-label','Taxis en Comalapa');const info=document.createElement('div');info.innerHTML='<h2 class="mandaditos-titulo">Taxis en Comalapa</h2><p class="mandaditos-descripcion">Servicio de taxi a domicilio y traslados a tu destino. Consulta disponibilidad y tarifa.</p>';cuadro.append(info,s);pedir.closest('.mandaditos-acceso').after(cuadro);}s.onclick=e=>{const d=dialogo('Solicitar taxi',e.currentTarget);d.querySelector('.mejora-contenido').innerHTML='<form class="taxi-form"><label>¿Dónde necesitas el taxi?<input name="origen" required maxlength="200"></label><label>¿A dónde vas?<input name="destino" required maxlength="200"></label><label>Personas<input name="personas" type="number" min="1" max="20" step="1" value="1" required></label><label>¿Cuándo?<input name="cuando" required maxlength="100" value="Ahora"></label><label>Referencia (opcional)<textarea name="referencia" maxlength="300"></textarea></label><button type="submit">Solicitar por WhatsApp</button></form>';const llamar=document.createElement('a');llamar.href='tel:+'+normal(config.numero);llamar.textContent='📞 Llamar al sitio de taxis';llamar.className='taxi-llamar';d.querySelector('.mejora-contenido').prepend(llamar);const aviso=document.createElement('p');aviso.textContent='Puedes llamar directamente o completar estos datos para solicitar por WhatsApp.';llamar.after(aviso);d.querySelector('form').onsubmit=e=>{e.preventDefault();const f=e.currentTarget;const msg='Hola, necesito un taxi.\nPunto de salida: '+f.elements.origen.value.trim()+'\nDestino: '+f.elements.destino.value.trim()+'\nPersonas: '+f.elements.personas.value+'\nHorario: '+f.elements.cuando.value.trim()+'\nReferencia: '+f.elements.referencia.value.trim()+'\n¿Me confirman disponibilidad y tarifa?';window.open('https://wa.me/'+normal(config.numero)+'?text='+encodeURIComponent(msg),'_blank','noopener,noreferrer');};};}
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',iniciar,{once:true});else iniciar();
})();
